services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensure file watching works
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" # Install dependencies and then run the dev server
